default: &default
  adapter: mysql2
  username: <%= Rails.application.credentials[Rails.env.to_sym].dig(:database, :username) %>
  password: <%= Rails.application.credentials[Rails.env.to_sym].dig(:database, :password) %>
  host: <%= Rails.application.credentials[Rails.env.to_sym].dig(:database, :host) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: file_stashes_development

test:
  <<: *default
  database: file_stashes_test

production:
  <<: *default
  database: file_stashes_production
