
default: &default
  timeout: 1

development:
  <<: *default
  url: <%= ENV['REDIS_URL'].presence || 'redis://127.0.0.1:6379/0' %>

test:
  <<: *default
  url: <%= ENV['REDIS_URL'].presence || 'redis://redis:6379/0' %>

production:
  <<: *default
  url: <%= ENV['REDIS_URL'].presence %>
